---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  DNS_DOMAIN: home.arpa
  HOSTNAME: homelab.home.arpa
  # MetalLB IP allocations - must be static IPs outside your router's DHCP range,
  # within your home network subnet (e.g. 192.168.1.x).
  METALLB_ADDRESS_RANGE: "10.6.1.10-10.6.1.99"
  METALLB_TRAEFIK_IP: "10.6.1.80"
  METALLB_PIHOLE_IP: "10.6.1.53"
  NODE_IP: "10.6.1.3"
