apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:tfeeQArw5M+b4zR4fb3wQT71BuDDtGsPCmzKsXd8Xw==,iv:GlMNcmfhDtMetpIH0GAecwy5YiD85/OyB1O+bm3mKG8=,tag:zFY79kKtIuJk3/As/WT9jQ==,type:comment]
    admin-user: ENC[AES256_GCM,data:TuAE,iv:e+yoCB6kD2dOhXbWN7G8GEiYOgvW2bx+4/VJjClOrHw=,tag:Dt84mqBw/GPuUxNIs4y7hQ==,type:str]
    admin-password: ENC[AES256_GCM,data:+DpoCymCY+kHeXWrVcRGUzhY8UTn7IsXbOhXf5B8opc=,iv:hYhOKln7N+0HvdR1izXcHa2MXFtjEYz6aO2sZwFimso=,tag:mPT/zpjWRBJ8q10LMRrnkg==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRHdDV29PT3JkdW9OejNl
            YWl1TmdjOWViSkh3UmIxd2Fyak5FREdLdGdNClFwMnM0eHA2dkJXbXlDRVZIZ2Rp
            dGlTL1NudVEzOWZ3NmdqU2daUEdHYkUKLS0tIGEybkwraDN4ZndiR2xxdm5KY05a
            QzQzbGhPcnNBQUMvMnRSYkRiT2h5QU0K2/0OMQt6hAFxQlnQnWAQUHJhWi3an37C
            GjJyPN2wC6WvdqNOEL+pl89fYbaX8ofaDAdnAnfKEIz2Eve8JTbdPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T22:58:30Z"
    mac: ENC[AES256_GCM,data:FWNcfWwr4Srx2Q6xxNj6TjlTZ89WSLpvG8KBLp5bEKfzjkOzjFILQBByKvfLb5coRJEs/fTshPTd0/0e/2NCOC4V0cebo82lXVriVRnoPi8DzT1FilnbfJposLRsd5kxLIxT/qw6IYaVZZ+zk1DpySFALgNBya4+syP7/vlz0Ew=,iv:oNbpXPk4LxfyWIIPgGKbIwPe5nI005rmygwAg4y9K1U=,tag:gwe6mfkwqRaEeMQtEh/nYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
