# yamllint disable rule:line-length

apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-adlists
  namespace: networking
data:
  allow_lists_request_body.json: |
    {
      "address": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral-native.txt",
      "enabled": true,
      "comment": "Set automatically by script"
    }
  # Heavily influenced by lots of nice folks on the internet. In addition to the authors,
  # https://github.com/stevejenkins/pi-hole-lists/
  block_lists_request_body.json: |
    {
        "address": [
            "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
            "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts",

            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/fake.txt",
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt",
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/spam-tlds-adblock.txt",
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/dyndns.txt",

            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd7.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd14-8.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd21-15.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd28-22.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd35-29.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dga7.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dga14.txt",
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dga30.txt",

            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/hoster.txt",

            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/doh-vpn-proxy-bypass.txt",

            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/anti.piracy.txt",

            "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt",
            "https://big.oisd.nl",
            "https://urlhaus.abuse.ch/downloads/hostfile/",
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt",
            "https://threatfox.abuse.ch/downloads/hostfile/",
            "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware",
            "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist",
            "https://v.firebog.net/hosts/Prigent-Crypto.txt",
            "https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt",
            "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt",
            "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
            "https://raw.githubusercontent.com/blocklistproject/Lists/master/crypto.txt",
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt",
            "https://adaway.org/hosts.txt"
        ],
        "enabled": true,
        "comment": "Set automatically by script"
    }
