apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: networking
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CT6m1QODJ4sLvs2Ke6rD0pRUCHd3FsBPhRQNYsPV3+eCSQ9o5sHb+cTEHI6gaXGvzTrRmgvLnAkpxA==,iv:jkLd0V6bELMrlhIG2WbzBH+HkRyzI2z6ancEMwkuh9M=,tag:+T0G5d787prnxudqr55Lcw==,type:comment]
    FTLCONF_dns_domain_name: ENC[AES256_GCM,data:w7FsLoKti/s2,iv:7kDRRzYU94v7QYOlT3AKB+506LcQ48d25zTYSOVpavQ=,tag:bh3h/WwY5m3lsloxwa/o3A==,type:str]
    #ENC[AES256_GCM,data:8B3S3fHqhdXs+5KiIH6V1KiIuODdusVoeyu4Kse/7Y+c9xp6puRoCHRUjFPJ4LHIdQ==,iv:YhLFPJwglv4FSNccDE9TTR8TmjGla2FxrlnOPhYDhY8=,tag:+g87Ld40HCKtFw2p8srA4Q==,type:comment]
    #ENC[AES256_GCM,data:JcFRYDumiMhuMQz57fOxuE98qgnssAuvPSWk4g4NGQy/JTdP2Q18Ukxntd66QJjtyznYIEQeHE2g1Z3tpc1pBuvMxUIYmEE=,iv:CbO31sX7vIG+FHkqnlycmUUfWFOLJYcLG8Bu379FDGc=,tag:DDIAbXPv71weaDXO7Hz6LQ==,type:comment]
    #ENC[AES256_GCM,data:kKZRrKtvI3utCzZmumNxBEnGapgmJOU0pfBU/cj1WQJMgsQ9QXspqFW+dLqFU4RjdictOVcFlZmbyhHyoaleI8bA7iYwgaTGz8Qsk2NPyYRPCqs=,iv:p8/H01y4PLPflvyfbWRNfK403q2ebtz8aPkPG63142E=,tag:VVkpR3OMd/jjgwzbtUPA+A==,type:comment]
    FTLCONF_dns_revServers: ENC[AES256_GCM,data:q2XpKa6ntIcIVPfw1ZZ8h7rI57hnt78qNBEvN6hSMeiX3Vs=,iv:FtJDrnD3FWZWV5yBlHtvXTKB2sJejHM01oV2rFQoSSA=,tag:EFNWG/WpJy5J/l+7Dq6qgQ==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbld5bVJ3eWxkcFE0eGJy
            bWVKazE0UVlSci9sWjByMUNHVDVjZmxGNWs0CmZzdm5JUHhxK3VnbENhTVVPVklu
            UkFiM0MvYmdDK0JSM0VINlA1Q1E1QlkKLS0tIGVNZlNRL2tpMUJ4ME1LVTg4WVo0
            RzFHQ2NuRVRaeDNpajN5d3drNnJmRU0Kg8qyh31oPOwGhIeyEf9kmIMCO+dBy/K0
            3blS5F7YVJ+eMFNeeo913MLbfzr4CGI/UN3xUVcJq9QoH8LL3A+wzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T02:27:57Z"
    mac: ENC[AES256_GCM,data:MjedFjisE5XmePdZ3sV1WBpeDMplEOeLTXC/EOaHUlmyP5Rlu5e07eK9Djy4yDXb+ylT0F1oGt97HgFEEXXIh+y40kYgzgbZ17mUcXM2b4aP4JuTXaxHMXfcck9di7F9kGBBauZSlczHafd5npGN3BZOkJXg9uMbBR7Yl4NwCzY=,iv:6qY45wmX1riCBMxHbUXLRrYnt0oYpuwfaKxvxnkwY8w=,tag:pbXxuu36Uf5RLPr1dqZR2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
