apiVersion: v1
kind: ServiceAccount
metadata:
  name: pihole-config-sa
  namespace: pihole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pihole-config-role
  namespace: pihole
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pihole-config-rolebinding
  namespace: pihole
subjects:
- kind: ServiceAccount
  name: pihole-config-sa
  namespace: pihole
roleRef:
  kind: Role
  name: pihole-config-role
  apiGroup: rbac.authorization.k8s.io

