---
version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "/infrastructure/homelab/dns"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directories:
      - "/**"
    schedule:
      interval: weekly
