---
version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "/sites/akron/apps/network-optimizer/base"
      - "/infrastructure/homelab/dns"
      - "/infrastructure/homelab/metaldb"
      - "/infrastructure/homelab/monitoring"
      - "/infrastructure/homelab/monitoring/unpoller/base"
      - "/infrastructure/homelab/pihole-sync"
      - "/infrastructure/homelab/system-upgrade-controller"
      - "/infrastructure-config/homelab/metaldb-config"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directories:
      - "/**"
    schedule:
      interval: weekly
