---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - unbound-configmap.yaml
  - unbound-deployment.yaml
  - unbound-service.yaml
  - pihole-pvc.yaml
  - pihole-secret.sops.yaml
  - pihole-deployment.yaml
  - pihole-service.yaml
  - pihole-ingressroute.yaml
