---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: klutchell/unbound:1.24.2
          ports:
            - containerPort: 5335
              protocol: UDP
            - containerPort: 5335
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/unbound/custom.conf.d/unbound.conf
              subPath: unbound.conf
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            exec:
              command: ["drill-hc", "-p", "5335", "@127.0.0.1", "dnssec.works"]
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["drill-hc", "-p", "5335", "@127.0.0.1", "dnssec.works"]
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: unbound-config
