---
groups:
  - name: Streaming Devices

clients:
  - address: "10.6.30.10"
    comment: Roku
    groups:
      - Default
      - Streaming Devices

allow_domains:
  - domain: tags.tiqcdn.com
    groups:
      - Streaming Devices

block_domains: []

allow_lists:
  - url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral-native.txt
    groups:
      - Default
      - Streaming Devices

block_lists:
  - url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/fake.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/spam-tlds-adblock.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/dyndns.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd7.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd14-8.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd21-15.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd28-22.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nrd35-29.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dga7.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dga14.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dga30.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/hoster.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/doh-vpn-proxy-bypass.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/anti.piracy.txt
    groups:
      - Default
      - Streaming Devices

  # yamllint disable-line rule:line-length
  - url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://big.oisd.nl
    groups:
      - Default
      - Streaming Devices

  - url: https://urlhaus.abuse.ch/downloads/hostfile/
    groups:
      - Default
      - Streaming Devices

  - url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://threatfox.abuse.ch/downloads/hostfile/
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist
    groups:
      - Default
      - Streaming Devices

  - url: https://v.firebog.net/hosts/Prigent-Crypto.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://raw.githubusercontent.com/blocklistproject/Lists/master/crypto.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
    groups:
      - Default
      - Streaming Devices

  - url: https://adaway.org/hosts.txt
    groups:
      - Default
      - Streaming Devices
