---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-optimizer
  namespace: apps
spec:
  selector:
    matchLabels:
      site: akron
  template:
    metadata:
      labels:
        site: akron
    spec:
      containers:
        - name: network-optimizer
          env:
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: network-optimizer-secret
                  key: admin-password
---
apiVersion: v1
kind: Service
metadata:
  name: network-optimizer
  namespace: apps
spec:
  selector:
    app: network-optimizer
    site: akron
