apiVersion: v1
kind: Secret
metadata:
    name: network-optimizer-secret
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:MA4dLT5GXXY=,iv:8I2Mal9owGRBz288353aDRwPMkhUVM22iy9McNOgIso=,tag:cN9mPq1IVQzfdhbKiWimWA==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN0ZDcnRkbmo3b01zd25S
            MTB3WDk2MzR3T1hzaDJkT2Z2Qld4dXQ4ZDI4CjZXSy9jM1RZOEFtRUJxa2xWK2xY
            L0tKM2J5YkE3UUpOVUlLdm8vSUx0Q2cKLS0tIFlQRk54eE9JS0R2VXY5MmREeGdi
            YWRhcUd5OGNaQkZhczZGbVNCRndlc1UKaT+WAsIkXPfj7vH02hOnZGmiodWrAWpQ
            lcNVIVN24RgJ9njLrH5MSL4r7IZETbWF/ci2Tdax73bJZZnArVkIgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T20:27:57Z"
    mac: ENC[AES256_GCM,data:9rz576lMuzszTZVIgIqij1M5FQ/uCJj1SY5EKErbqv0g68zDS+dmliBYph7Guj0xEBiathfQ7Kny57oy4s90HjaLPshXojcXosBJQmOdMxFplUBZ1NLe1GW++mtf96PI+7R2VSda4LhedniQxZgPTnS29EeqnxP4PlRNU6NTxfk=,iv:SM5f/jXG/KILGRJuHI36seRW2QsJkU1B8BfmHSRcTHY=,tag:T1l1cj2Fm3J8HcaDphd8Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
