# Podinfo IngressRoute
#
# Routes:
# - http://podinfo.${HOSTNAME}/ -> podinfo service
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`podinfo.${HOSTNAME}`)
      kind: Rule
      services:
        - name: podinfo
          port: 9898
