# Middleware for stripping /podinfo prefix from requests
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: podinfo-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /podinfo
