apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7ywJs2UUJAGZl5uLTwQvyC7BJD1Ij5PSzMtIWeUlhVksUK10Ceq9LovvuYWdhP459srPRiY=,iv:pQxEkZ84mc//RnbbzamseISDjK/edTxbfPJ1whx+SKk=,tag:L74XAiCtaew7p9AsRTzt0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTGJiRnV3eGhwWDFjd1pL
            eExhbVQ1aXZMWU5PNHcyNzJ5T1FQdTJqT1VJCnJ3N1ZWNk10S3ZseFJNY08xVHdV
            dXNQQTcwakZFa0F4REJlTmlWSW5CR28KLS0tIDF0WVlqclc1Z2E2VU1MeFB1QW9Q
            NERBM2k3OFVnUjlDNlpEd2dvTG9LS2MKfDwZ5DNxiqf6hKtg+Nho/Z7tZVQg1IgQ
            R9Dn9AkPo7ey3MhBQMRQUW6gQ+9lenSitu1i6v2X+CtLG1hgRUQOtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T06:25:56Z"
    mac: ENC[AES256_GCM,data:OZ3XKYVLyFF59YrGrpleConwVZfrA0DahpjjnEsBCzRzrq+oYOfEHVRxNGVwyIsNA528xgnsBrIHEVpepW2hFuhbVN9VqguKNHLhM1P3ktOWllXdfFiWp/FDITQ/68oMbz13hOJEoNwI8EIcYTiFDkC6MLQoWiUFeBKDfnRMEmE=,iv:OJ6c1/yhJyAYBzmWwee01yYYAoDcQEkkydZBzphW+9s=,tag:UrwxYuw/zQMqZj4y/PLdDA==,type:str]
    version: 3.13.1
