# Pi-hole's admin password, in the dns namespace.
#
# The same value is in sites/akron/apps/pihole-secret.sops.yaml,
# for the other namespace that needs it. Rotating means editing both.
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: dns
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:dtvxFCUzH88TV3f0dYg3IcAsu5ZvMJkRegiGVqSclxs=,iv:SF5Z4aFmp3Oa9f51DJyiV1RN0orztdzXEqgfwm8/dHo=,tag:hFbADAW99NqvfgYeLOOg2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MTY1QVNoTExVYWdnS0pF
            TC9YN3JobUREbDZ5bGQvZDhmUkdRdkpKSmtvClFFZ2E5ek4yWWxTL2FqdWNyTEU0
            eWFZbjc1QitDanBFb0JJbHV4QXRvYlEKLS0tIDE4clpvcmxrOEl4M1BxNVhTWGtq
            MFNOa05qZEovUURza3FBcjZWWlJ2cDQKk5/KU+pJkGJf1lgPupt/4BdaSLRwgiRx
            zF1Q0HuBhBcaqxNSMDnGJU7fdQlOxuKX5rWrdOeQm/NIqSPDMocIjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T05:14:18Z"
    mac: ENC[AES256_GCM,data:ISbMnrH+ejT7L5BWbXvUreUJFO4WFTqFNtVEB1BySC55Cojl08fmlsWSwTvx21vM+YifiFKH1HSouHxULWcn6YL64BeuqOoQalHqDoUZcNSaauMhUgtaPv8LjJzHzgDt5bnFE51pvyAAdYx3YHNpZXVmpUAUnNokw0cz3OLTeQE=,iv:bo0NA3Iu5ECdaOIhM4IZSW8G8UpJ+5Qs7bcQlj8QMJY=,tag:YNiBntHR25eNc3hvogKA0A==,type:str]
    version: 3.13.1
