apiVersion: v1
kind: Secret
metadata:
    name: network-optimizer-secret
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:YuyOatkOkqE=,iv:JlMeklTno+PTJ9LfJZj1Gt/930EtIuo1pcO0eYhj9XQ=,tag:7GdChhy1WjTR2gAS8KihKQ==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYzhUb0dlcDBGMkx3TEI2
            NFJoY1JqRzZHeEdUUjNuZEhMRXIvaGxYRlFFCkJxZy9oSWRYSnhkNGt3bGpXVGdN
            QWtLa3lHZ1U0eDZJSVE5S05abTlGbWcKLS0tIGxNUnJTVFFsME5RV2xKMDNtREF0
            Und4Tmkxa1hJRndJdStDbWJoNThNNVUKZk1OOP5rb6rEBqr7IZIvY2sGelxpjN8W
            4bzo7qV9HkSw/U+V3SZY3D3nlkMtiSjE+Y+oQb7LQLY/BDkd9ATBwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T01:51:32Z"
    mac: ENC[AES256_GCM,data:HwkOs6jBnRgDi29do8H3IzafY2X7zt0GpbwX1POmOf0E+K5suToiWRZE3gW/7Ey9R6ZfUbqkAvrI0bASH2KYOGa+XtGaK6Z7glWM0HTSOz8d/j4Pmhcj1G0u/ia/oK5oHld5F0rl/3/faKCM9j9h0kN2t2MIWoMBeIA1U4IEVGE=,iv:moI1wZtc8s6nBk/2Oa8deagCwHqgexkldjEpfWWLnRA=,tag:Lh2/3lEX/eahtAQPB3ONrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
