apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  # Upstream DNS servers
  FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1"
  # Enable DNSSEC
  FTLCONF_dns_dnssec: "true"
  # Listen and respond to local network only
  FTLCONF_dns_listeningMode: "SINGLE"
  # Listen and respond to a specific interface only
  FTLCONF_dns_interface: "eth0"
  # Do not forward local domain lookups to upstream DNS servers
  FTLCONF_dns_domainNeeded: "true"
  # Disable UI password
  FTLCONF_webserver_api_password: ""
  # Timezone
  TZ: "America/Toronto"

