apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: web
          protocol: TCP
        env:
        - name: FTLCONF_dns_upstreams
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: FTLCONF_dns_upstreams
        - name: FTLCONF_dns_dnssec
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: FTLCONF_dns_dnssec
        - name: FTLCONF_dns_listeningMode
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: FTLCONF_dns_listeningMode
        - name: FTLCONF_dns_interface
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: FTLCONF_dns_interface
        - name: FTLCONF_dns_domainNeeded
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: FTLCONF_dns_domainNeeded
        - name: FTLCONF_dns_domain_name
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: LOCAL_DOMAIN_             
        - name: FTLCONF_dns_revServers
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: CONDITIONAL_FORWARDING_
        - name: FTLCONF_webserver_api_password
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: FTLCONF_webserver_api_password
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: TZ
        volumeMounts:
        - name: pihole-config
          mountPath: /etc/pihole
        - name: dnsmasq-config
          mountPath: /etc/dnsmasq.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: pihole-config
        persistentVolumeClaim:
          claimName: pihole-config
      - name: dnsmasq-config
        emptyDir: {}
      restartPolicy: Always
      # Use hostNetwork to allow PiHole to be accessible by IP for DNS queries
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
