---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - secret.sops.yaml
  - podmonitor.yaml
nameSuffix: -lottage
patches:
  - target:
      kind: HelmRelease
      name: unpoller
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: unpoller
      spec:
        valuesFrom:
          - kind: Secret
            name: unpoller-config-lottage
            valuesKey: upConfig
            targetPath: upConfig
        postRenderers:
          - kustomize:
              patches:
                - target:
                    kind: Deployment
                    labelSelector: "app.kubernetes.io/name=unpoller"
                  patch: |
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                      name: unpoller-lottage
                    spec:
                      template:
                        spec:
                          containers:
                            - name: unpoller
                              env:
                                - name: UP_UNIFI_DYNAMIC
                                  value: "false"
                                - name: UP_UNIFI_DEFAULT_VERIFY_SSL
                                  value: "false"
                                - name: UP_UNIFI_DEFAULT_SAVE_DPI
                                  value: "true"
                                - name: UP_UNIFI_DEFAULT_SAVE_SYSLOG
                                  value: "true"
                                - name: UP_UNIFI_DEFAULT_SAVE_IDS
                                  value: "true"
                                - name: UP_UNIFI_DEFAULT_SITE_0
                                  value: "all"
                                - name: UP_LOKI_DISABLE
                                  value: "false"
                                - name: UP_LOKI_URL
                                  value: "http://loki.monitoring.svc.cluster.local:3100"
