---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - secret.sops.yaml
nameSuffix: -lottage
patches:
  - target:
      kind: HelmRelease
      name: unpoller
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: unpoller
      spec:
        valuesFrom:
          - kind: Secret
            name: unpoller-config-lottage
            valuesKey: upConfig
            targetPath: upConfig
        values:
          podMonitor:
            relabelings:
              - replacement: unpoller-lottage
                targetLabel: instance
