apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:DTYnhttegK2Mm+svlTkrwcTvZED2Fe7e4w00+GqHCv2P4WaZbujK+R8wkI0+8Goe9ScGv7gUOaXOcGKYZfJSbXPX5RzAYBo8GdGInzc5U+9mFbWRBcDLoZ7+Di93SENPq5QVdcd0eTzeGjvJv35utT2gJ8BmhSIbIuYoplWivs7l3dG1PtzY+B7TY6ihq+FO8evwFEQGSZiSR/cU2DTlpLWaaudIdDb9oFD+5Uvy3ufWZu98t8CWPfz3AAvW7PxIGg==,iv:2JxnYLKTSyVSqneRdNgrcSx3AycSzR+GwfmUOQgNVY8=,tag:99z66hPs7+6K5krf6MWuqw==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY0JDMDhMUnhDSDNja3po
            TVgyMDRRM2oybkVJcmR5dDZ5VDFtMks1NFcwCndCQ2UrUm13VCtpVVhuL0lsNUM3
            bDZvWlU0U2xYNVBoajlrZjE1SG1vSGsKLS0tIDFGU2NJdDBVcm4raHFBZUFRdWgx
            eVp6K05RYVh2dXhEWGM5UEVtenYxNFkKO/tYL19BcUwfcOADwvVqKTwl2CcuTN3C
            OVHFjn2wviM6qsNlrdgtDGyzIVvgoINdFXHNSiBPXLV6UI78KnZYxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T05:20:53Z"
    mac: ENC[AES256_GCM,data:jpFZgr1eaZKF0cJ/DGU5COWKQpHsNaUU9UL8i859MNJgqHX7T5GcLVB98esuaerqNRtjUQ9vXZm2hniXaAp9z5tn0ATn7Nxi67bb3nG74UN4DtjiJGLgS5l5DpeuK+BnNgroXhFZgX/lgKExHCBQCo/ldvNGgXPS1ouxEwLPMho=,iv:gysldWG69z8cJVY6Kud7ZkEIHT6qwo3EmcHd0QJl6NI=,tag:2cZkzkUaVgjO6lRcx2gZjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
