apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:YBRf5D5M/KjIYs6W1tAyjXMAR2FklnXgk8j5FzYASDA4UE/FyNJK7Jaw9XhAgwjv4gmZaoo2JjDZ7BkCSjEubgfMKvlrgydhYWm6fWwFi4jDF/qu5S6Xo+8IMcnlwi8ulg9RCS8kwifYdytnrqo+hym5x3CHhk50PmKbXdY3bjoH0D/U8QPjL4H3YoxFaR7KuadW9ZAaR8Qz4Ht9a4fF4PTOFQOMJzXRhlnDbQ==,iv:wNadG6wQU2XFpOFZRjyXyMPFgMDKW3/Hx4Rejel6wYk=,tag:nkoOBRM3lLTQAIo0qU35kA==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTEJFZkdDNmdYMkdsWEVK
            SXVzY2loemF2WmlzZ3ZxN1Q3bjB0VzVNNm5FClFTa3llQjJ1bm5mUzQzSzVrQ1Yz
            cjJXU244QmFjRU1TWDZvVnpWcTd4Qm8KLS0tIGFjWkJKajdNWmJoeDRpbkdEZ0pC
            S2Z2a1UxSUJPRFJ3NG5neFE5TTNyUGcKw4XoG4wOUpPfaTXWeQ0a+KPX7wJeWN/1
            I1EA0I8tlmK/vUJ4FjQzV4vrWpelxsVT0ZFPQ7/GQKRn44giYFBGhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T01:29:47Z"
    mac: ENC[AES256_GCM,data:UdJEsOElYP96evZaaz2lMHv9o34es1XuxJiqFIhSWpt70G03gRbF7mmerT6SsxOHp8843KyFcHOFFZ7QGRYhViFy4Vj7hsk7qU1FElrug/K+QHqcPjMXmsd31/8RN8Wopnn8n9feOAoaq2RknRRdMsijskci8PsLF/qG4PdaCwQ=,iv:Pf7WdTVpKxYEhWePx2USYYmYi7i6iW1q3dulvIhy2r0=,tag:3D/Cztmcr6J6sK8Wj+DwrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
