apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:d324IT1e3ld8OJfZNGbbWr8qSpYI8C6fg3S0UOm6YdJrsu4NW/E8N7DlgbaNf5A9tRlmwD4=,iv:YJ+vEG4F02XSshUcbX4f5M8Bu32+B90BM50Sh7wHvvU=,tag:so1CYk2zInPAj+N0GYbL2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb3FnZnR1QkJKUkRYTGZQ
            QmxVVzJrYnFEMVJUbDBuc2daK0swWFN5T1g4CmRjZHZrYUcydG5ITGZ5d2FvS3d6
            QXg3a1M4YlZQaldaM2NrSnRzQ1BUYlEKLS0tIHh3Zkt5L1hhT1J6bndSMXZCRm5O
            WEJzUTYxQ1Z2TEZxbjJxbnZadjIyVDAKoZUDpt3zp8Q/qCk5Xb3uHfXH2sDu9Mn2
            UGWdQYTur8j1QqnV4jgNBy6qX2rk4Jlf2lAnuIw4j+jZGVbjKkMxJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yg55rt2u8q9tc4jrxa4ve4pg7aesa8vup83wlj6sxvyjqj2cqccqspgz4f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T06:25:56Z"
    mac: ENC[AES256_GCM,data:p98ck6J9EMHHpsZzW+MfbFzZsvS7k6kpRz5uCExpXOj8A05J+D6IMhVPV3XCKLhtDy3sgjZMRR7XyNiSV9GhcDcdKdcy4qXV0vrnyrtMBbbWm8dANepDd+hfSBN7Gj354AStTX5r4VY6wgiHpZ70TTuw8+W842NSt4CKGaFUnFE=,iv:wStd6YXdg8HOfocfpbmkvoM33YsUbQXlaCn2kMh1Rr8=,tag:RWB8hgwEH806NgdnhA8dBw==,type:str]
    version: 3.13.1
