# Pi-hole's admin password, in the dns namespace.
#
# The same value is in sites/eastbank/apps/pihole-secret.sops.yaml,
# for the other namespace that needs it. Rotating means editing both.
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: dns
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:2lP812TPYGwHD2awqBc27fse+JsCBJjOK5hOxpCOC1M=,iv:gzDnaUwbLqnjx0FDXXjRjSZKR3/c1yQEqShO3YSuwBY=,tag:vCyyiEHKm3H3mLdYIFvejQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCR3o2L1dXcmM1dmlTN1Nr
            N3R5eGM0T2ZXK0NMNGhCb1V2UDRGSmE5cEFNCnlvTDcyR1dicHcrL0lGaGZnL3Vj
            NUpMaTVKTnpaTVR1Z1hNbGlxMUR6R0UKLS0tICtTMjAxSDZkdjR0cFp3b3VuYlJv
            T05QcHdKK0JISGRyRlV4VUtLZXkyMFEK0exVh5aaLdinpgVD7dMkZlap8ZhPzCcX
            nq5z+qZ6jGIy3q181BpVIAWSvP9qDVTeOeIQN8m9bLn11hrFxER5Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yg55rt2u8q9tc4jrxa4ve4pg7aesa8vup83wlj6sxvyjqj2cqccqspgz4f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T05:14:18Z"
    mac: ENC[AES256_GCM,data:DpKyZ0T1PWWt1sMS9XpYlbFmOv5eZ0f815Ukl9fwaWHHC9NKSOc4hOoo/htv7Wl1zWpJE4DSWfqKOldbjoj3nHgj+1hlLiHCeq+WaDCucqUFF6LHTXRvHB+g6qgykDQnUGnZZA6No3ka4ugO00XG6ASPrW8ld5f9kEz6o5nvDUk=,iv:wFtkQUvlSKJZtZ3QQlkSy/TriVYqf9qy8D7j25NGAGU=,tag:7RdZGqg63sXoVyFCj3pNFQ==,type:str]
    version: 3.13.1
