apiVersion: v1
kind: Secret
metadata:
    name: network-optimizer-secret
    namespace: apps
stringData:
    admin-password: ENC[AES256_GCM,data:XrQlpTLLIBs=,iv:nomN8LYNI+k4wYL/+URjPVMqZnFDFGpo7+N0UHQAl98=,tag:p1ph+JGoyvJiO4VDqgw2tQ==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc3Q2WTVlcTB2cXpza3Vl
            UHlPNUpXRnZpTEFDS0d6V00ySEFLTFBLeENZCk50Z080OFh0Y0YyQllEU3I5UE9H
            aXBITmw5alMxN2F0SVdVb0ZoM29pM2sKLS0tIG5nTDBKRGI4d1g2WVZraUpDVHZZ
            VkVUdHpTUUxQRERWMlhzbkEyR084ajQK2YCOa288yE8WDOuxSp3alzQs+cXCh5m3
            H0WvovXt6tSWTKk/BrSJqIHVXbxGZrr1S2HJBL1Zp1FRYb3vxgZY5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T01:51:18Z"
    mac: ENC[AES256_GCM,data:P9Kn+QIkrHMvvPbsAudq6/7q0DaqAsSC58aRJPy15TTdMmhA80x1HlJ0mpJwImnvBaya911ZVXxmRf13YyDgdZcqs9E0BklCOSX47hk2Nc5yTWOL34NTQdpXw0M2UHm+/0pezdpGq+3MryBNgeMB+yd+kZQ7eFLhWeV6Rbq4wRk=,iv:2RlkqOhIDlqZ+AETDFdDwl9M7S0yxJmVlbC784Vy6L8=,tag:gduKgjF6EDhc0P9Ck5pF2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
