apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

resources:
  - namespace.yaml
  - unbound/unbound-configmap.yaml
  - unbound/unbound-deployment.yaml
  - unbound/unbound-netpol.yaml
  - unbound/unbound-service.yaml
