---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unpoller
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: tcp
      interval: 30s
      relabelings:
        - replacement: unpoller-akron
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/instance: unpoller-akron
      app.kubernetes.io/name: unpoller
