apiVersion: v1
kind: Secret
metadata:
    name: unpoller-akron-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:TQI55VWgR4pJZn4Eyj7CHYvwtRzkRX5RNPmfhBQ6EnfDvc93qSSjY7pxGckUVT1bq/uTpBleUvUDa2dHSRDdB68wnO24NIfjzJ9sj6k/5wCQBa6MBqwfQVrPRlNseg3AdRRwqEqfARbpwqU6DlT/GHtSsaYD881q+9Mi2WboynT/Tx2F/PEkLx61aDYXX8yiztzmvdg3B7XGEuCzYLwSMJb+CWhmBzZLTR15CZbWioRfE9KXzY9m75oWymDGYh1zm7g=,iv:LQHfYeVM+PDjupBYYaM4282a7ki0yzbcL0p6+p96PMo=,tag:diauB1Bqu1JkXiNuVS3EYA==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bTlEMXU5T1g1ZmdjNkUw
            dkN6UStKYnUyZ3dQbDBLaE5lbDlpWnNqamhRClNRWDVJOXJvbWxyM1RVNjlSWW52
            SkloNERwaW9UY0taNFVGV1lINkZoZlEKLS0tIExOcDhvdnJQYUtDMlNPS3o3VkVt
            V0RKTHg2cFJlSFR2azFrc1RaZDlnRWcKo75vV0ubZvkBVPX9EieTJpamrZLIofYr
            JJf9yYqHiqxDCLKB00Yx6WNezniqakg0qQEEE4Uhd0jrwLlXojCjDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T07:54:40Z"
    mac: ENC[AES256_GCM,data:1GTHsq7VYsJ17FBdOcRQJmmQZt9glfKyAih18zyeIQc+kyLwLxa1fnWRHyDPowPienshXAMCddiDKH9xM5HSisRFSB9v+Res28VXaTu9B+mog84iUZdSr6zNwgLa5ggqeNqhVlsOg44bsKMVCbhQjlVIx/Mruv2AhYKLYbtQkXE=,iv:YTtNHGj1GMaH27rYEyjw3qg9Z8gYvkNay2vx617qivs=,tag:avt/E48DQk+BNkXSRf9sfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
