apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:rhsWZxyhMkcohNLbFSBD6H07bUoTZyNAatn3phW/227MKlns09koALqFI8NUWBUy5+3/icPrh/COr00UQ+5DYg4hjfbLL3iqHsHN0OKehSDMZQLNngoPXjNCor4wE7Fl0m+cxq4fd077m6EKfVkeAVD2U1UOtmLyz/tmguII48II7zCsisRTftZYEDX5jD2DX9DO5diO95R2n6dXOWkE+wiDYmBjPNwlTwBXXHOQD/RwF9JxTRRAE70Mqp4a7bZJqA==,iv:Nc0hNYSyyf4XAcacL/PhNybGD2BDjx3NZYDkw0W/IDw=,tag:t1EudGOKcnM3xJwvcSg6Eg==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcCtHazljbjZXSFYzY3B4
            RVpTNnZnRVc0aDBFbWxXRnlIZkZnTkszNXk4CjZod1NCRTJNZUNCMnVSUDBxeDhH
            QWVJbkpCd1F2V1BZYjl0aTBkZDlUNzgKLS0tIHJYRlJ5T3NhdTM3aXVoSncrWVV0
            c0ExeCs1WDdoYWFGbi9CN0E0cHhnOEEKFKf7IpJnVHl1JCZfLvROtG2bAGwAG6CK
            eXTtGgODfEsY43L436JPNToenvLuiaOBcePkh5imHxo4mHKzwhEDPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T05:20:38Z"
    mac: ENC[AES256_GCM,data:DK+G+rSSGkkEMRFyHVBN0tdWRI29TvLliLekYDighLAbg8MAhgYeDs9bEVw5HCBpSqn2xV2cY7qWbx85mBgSCWs/liGqovAVF+SD9dHAbxWvpCxVW9227CWeSGjT/+RGLSF+bWWJ367icWxir8vMI2KjzBhsSaXrIWxcGdAgNJk=,iv:BgI4semG5EaNbyBahELvxEaoKd214WX2I0ASfDzKPVU=,tag:eCyPijSSnyUoXHJKXLxhcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
