---
apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: monitoring
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${METALLB_SYSLOG_IP}
    kube-score/ignore: service-targets-pod
spec:
  selector:
    app.kubernetes.io/name: alloy
  type: LoadBalancer
  ports:
    - name: syslog-udp
      port: 1514
      targetPort: 1514
      protocol: UDP
