---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "~83.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    grafana:
      enabled: true
      adminPassword: ""
      admin:
        existingSecret: grafana-secret
        passwordKey: admin-password
      persistence:
        enabled: true
        size: 2Gi
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
          isDefault: false
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
        datasources:
          enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi

    prometheus:
      prometheusSpec:
        scrapeInterval: 60s
        evaluationInterval: 60s
        retention: 7d
        retentionSize: 6GB
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: [ReadWriteOnce]
              resources:
                requests:
                  storage: 14Gi
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi

    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true

    prometheusOperator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    kubeControllerManager:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeProxy:
      enabled: false
