---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-helmrepo.yaml
  - grafana-helmrepo.yaml
  - kube-prometheus-stack.yaml
  - grafana-secret.sops.yaml
  - grafana-ingressroute.yaml
  - loki.yaml
  - alloy.yaml
