apiVersion: v1
kind: Secret
metadata:
    name: pihole-exporter-secret
    namespace: monitoring
stringData:
    PIHOLE_API_KEY: ENC[AES256_GCM,data:Sxli6NTXasZroSH71WjsZVZXugNlsXqJjMmcpnlY1iqhYMzn+j94PbyoV2o=,iv:/ohMyr5D08ZUuxD99cl/LzlbiGEMTVwxZSowcKnkhYs=,tag:wUgNhB4nBzp6tToyZ58pqg==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cjNNYkVieWNBQzlpNHZR
            ZkNWK1RHRzcvRmpsWnVtYlorbGRrVFRkMndRClBoZzFjSjg4endGdVQ0RFhZUUxX
            RXlRM1ZjdGxGV01jYXlrOEVsL0E4VjQKLS0tIDhEdmpTbzRsTlJtNDN3aVEyTWhx
            b3JiNzM2VU1iM3E3UzBOc1d1cTgrL2MKWarcCc1jjCffcQiPehZc2si2ikHSXD4D
            VNwH1sNS1nscZlGOJ9+7WcWLKgLlsVR0YP3HYkdNRK4lcYn4jvjdqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T01:45:31Z"
    mac: ENC[AES256_GCM,data:9LogsxkUHFeUWy54ILFSEt0HdMkk2e4lU7vyFjPRrBt/Vu2YBOtOBjnA9cP5H+H/UVgYRqEAKxlBamfIK+MLKQVhQsIGegHU/3vOjvJfYJTxWSNa/ZqtJVwPBpMydVV4dmlOpw5MGnWiwkLtkENC55J1pFU+IAGV7LTL2fAME54=,iv:rK/BNpbjoZ02cJrolr2/FopIlhwoMvsi+4gsWmEgEXc=,tag:fJYMtNfR/uKiiRQC/RsEUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
