apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:C+Z4eCrnFmQYuahELnMACDyOUmRJfO3s7mQxX5mCctPfhjvxLoHFwkL8mJl6CTDsz7q7p5BcPgOeVpK/NSHp8/Qd6JunSScbTrn/FZQgKtn0KGljskYiuZSl1wHmjXO6P/3QUg==,iv:rB31hq0rCYKKY1aVa6GuOslYN0b7U+JXcaN8shqsT/E=,tag:Gl90z5CuQSn69KQtK2QtuA==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZW9PZlFsRlEyT1I3WWZj
            N0ovVHA4cHE3S2V2ak5oRGsydTlyYjRRamc4CmdldTBpZlhyd0dRR1FDSVBUaDU5
            bkZTVVdJRzJjVmtqcW1HeklxSEFXRFUKLS0tIDhId1pRbHdGU0s4RVh4eXBHL1hi
            UGdBSVhQeUEvVTFzU0ZpZDhtY3FNMzgKoi0YCkw60Km9T7k0lV6mZtEaVaGboVjj
            zlOb0KICIr4vTMEGrxIrmD5PJpZwzeoZJf7lOocBoCA7Ve+jhJ/tSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T08:37:14Z"
    mac: ENC[AES256_GCM,data:L3yRc6ANjC6dK6DE/jkhNWWehH2/mivQSAZTqYLMn1UwgxI5CmrEHyJnbYMQ66DexupDUIpJ+ziyicSo7T5OEW0S8gxlj2CW/X/Zm63N92h8rWhVf4gQ0aK4bL6mlxlZYC8ZR6FhHySeKR26bhJCwWzr6aumDVpZ/XpM+dadiFA=,iv:059YInIs1ItvwvwkRPzME3Zn9lvQA725gnAApeHjvJY=,tag:OjsI9L/b4djuNUf7v6jOWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
