apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:bhfL7dGUoxm6TUVSC5gVTDMc8B4LbYXCmSW6xKAu1WtfPOzHkN8lFCgvRM2iZd3nC6v/fU+iQAA+xdtu2GhY9L+c+nEzlIYwd8iuOIy1butZMe1s5jfQYk7oOc3HCYd42w1ZmQ==,iv:1w7weJcqVTtGL8vRWDUdyKPluTHf1zoqiS6930xDdzU=,tag:IR81SFd0T6CsclceIWMqxw==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYi9GK3RWK1F4WVhvampF
            b3NiQWtUUU1OOC9WcUJTT09odHMxMFlvTUFZCllKL3R6dTF3emNyeEJNbkx0MGow
            aU5hR2lGUVRENWN0OWJJQjJRa3dibkEKLS0tIDVlUnAwc1B1akVjbVRzY3Q2My9j
            bHl1V2VxUSs3NXNqQ0NBb1pFdHJDTDQKvRWq0fZonXknxx3pgtPSIXlzds9nTxrn
            VN+mDywDgdk1m2UZZ7w6DUlhtIxtjGQCPU130Z430fxaHfhDVilMQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T08:36:32Z"
    mac: ENC[AES256_GCM,data:ademSH/fgcnhbUvhZy+eMOKp5BPh3g+fTb5XdSnjo15BrQxFi4S3FcJJbOsQdOUuTXJi37S5HDqMX2qjGkPiuNZ9IMc/ze23f0m+4ntoyunQ/PkQt+sBr/Q8wBW+WY0FRmJkpC1pNC+eiXSngc2n+3ofC+YgFLZgSEIlR+wCQsA=,iv:/wwnmfU7xjXZcq8L9jVq37OnTLsP1pDFEVdgLa0Jv2s=,tag:sto22JHRw8Z5AmVXr6F4iQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
