---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./podinfo
  - ./network-optimizer/akron
  - ./network-optimizer/eastbank
  - ./network-optimizer/lottage
