apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:suDVWrq8ptMme1y7QAoWZPH1opRBdJoe5tyw5ft/rDZWik+vaWK2A2zOLM3kuZzUvr+HfSoK+Y4wp7nPbBgkDkuHJp1nnI5sKLTPszhPYYBAU70G+dK6WJhQH35PQF6ihMV4mQcNv/6pqWl02vfTS0IMyR+q8ZxgIiPgCxx+X37XvWpUYUw03sfj3/DwMMwNCYmzQPS+sVSwpOCzno9P5TO1Ea057qdNIr4jeg==,iv:hH1mLW99DYHIo7tbfYaQeoq8p8WBIv5pbjK7gPiEfDc=,tag:FMwIaPWKlP9prA53wG8wqQ==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNnpPVWFSQ0hzT004VitE
            SHdqUnhDUnErbzYzQ1VhOTY1a2c2UE44WTFjCmUxVUQ1WWpVdkFOeVF4eHFlWGQw
            Z283ZDZjUDZxMVhTTEw0TkVVQWZNcFUKLS0tIDQwY1ZVY2paanR0MUpHMXY1bThJ
            WjVjVDVuclRCeWl2bnFtRFNhWmRQR28KqsMzdqpAZUNSRQHK0eKnOiiyKR1Pd7Nv
            8MErw84zMnDPx0EFcSpNnr5U27DBSYNhTMtSJBHULB7N/dhsP5FLUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T01:29:16Z"
    mac: ENC[AES256_GCM,data:i3+Cn2zR6rb4n+o0T3SkhH+b/bOarNvyAqD6+tY02wF0/YpLQwzAdHODOY6JKoYWUP1oJQZ4f26+LJfZn5+2gxfLPqgfiiYLZrkmfLwV4PL+MeQKn2UMbN7/z9TwA1oUHCUEcPSjnjEC8daYKtcU8c4tMSugJDc+/E842qQecmY=,iv:l44seJd8QkFOu1W70QwdxlM0518LkQsvYA4ltsynujI=,tag:Y9BDDjgmT2qHZmZgyjbcog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
