apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:UuDLU21Pd9EFx9AOATEBJYaP015xxT5CC1K7FiOU27GO33lszSrprRauCLCyQO5G/H54rKmuYuRlghrGVclxTCebqR/euXN5zqwzNRQZmKofnpaOgzAlkFG/4ctwRKjyRjQ+QXiU5MYeMpHwwQDtf6d/RrjTnUpR+RfGNQ+4lamqj4kAvy7DlIZfv3BK5JEp3GubhK9oQT5y92lITksb7buV/aFoN2Y2pOunC5tIFOvW5Sz0rpCnf1LAgw4PHWtCrQ==,iv:ctprhaOgDSMYVUBeKAnR30EB0UtjUCDWOBf8seJds8A=,tag:0NNTtcWrZklp7kDFoDWrLA==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z09LcW1xeHRPZEZFRUpO
            a1QwNnBRUHRsTkV4UU5vU1lQTnpzcHdvdWdJClQ0TkV3ZCtXYW40cjF3QXdzZTlo
            MFhHM1RMa2YyMXFtUmVrUG9JbmxzRjQKLS0tIDR1VHJvZTVBZGY1YTdYZVhickl5
            YnppNzA1MzVGblJDSkUvUTgvWmFGZmsK/JqN4e2An40ZIOuJE9np6YjUEhxLV4ZG
            +tM0oUXTaJgRHdd7RkmF15mQZcK5uovR4qLPxziWD98CqssE945Yog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T05:20:46Z"
    mac: ENC[AES256_GCM,data:+xXeH98kH8E/3+Td4jHrEIZ5qkmfrUj0p597wMVHCK3XYWvCjQLalbbQgTUeS+DeN3qK6Sf7djSWqhnvNgyxvci2TYTYHMQEZUwsO8iUehKuvtcchPUCst5l0xDV9oS8/xjby3i1/6H8ky1kjRfzTnmDUMb4cbIo4n/u/BESwd4=,iv:/rCQds4vrfZUrpxPOVyFHMGOA9JVGxEAFVPtiCUID+o=,tag:wyo2+BeOaMkRFx4CpPEFmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
