apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: monitoring
stringData:
    upConfig: ENC[AES256_GCM,data:wq84ZDHpCtKjYogvQihO0630V54f2lvE1UlnkIoXC3r4qq4RKkifKx87mqNJ4xMMd0W29ct2Q9VrbASn0aA3vv7jh7qzGelIbjPZ0vVQSQECW8/JUPsEdJ1CQe6Fpmcplnclrw==,iv:1DLEMtF4Y7zL99Q5mccvHUwY21qefvYFJuHS8R5bMZI=,tag:x7A3UxHTkBp6RviiCT0pgw==,type:str]
sops:
    age:
        - recipient: age1wfqc89fy2a8l339nf2rlevclkkhjcy28jurdex6gpdjt8laa2sfqswl45d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYlMyMDR2ZDI1Ujd1QnBW
            Si9GYTFzdVAyYStkVTBJL3U2NEFZbE03ZmxjCjZwOElpK2xuS2tlV0tYU25oZDBJ
            WW50RzEwRDZwNXBZLzNwenNid05hUnMKLS0tIEg5d0hQdGZWczBpQ0YzOTRLWEhS
            WEZXSXlGYVBDaVhoZkM1QjRvdnp1OVEKUwyAhiE9IPcZmYquffFxVUO9jw51F2rD
            zGreG0QJzpenYUId4twsVyWqzLHnCcGx8jh97xSVAn9Yyy+mIOi00A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T08:36:41Z"
    mac: ENC[AES256_GCM,data:2DAfp2LScou3ua3aL8bv4gBF4jUqb2P3Fu99qTDidhquM/NLRwlOxvJLJdngfP6ihLGzb4pJQD5NO/zoZWv3YznBvCxw8BJiN9wgqlVEyzBRNKlLZMQZsvKZikZyOEzzCrfHwWQC4zIvGOE6d705CTPSaD9ysOxjLtI3+meCPF4=,iv:EswinwAGZiXMPQJ5VJwjhqCCzWnYoICPT5VqzeFtkSE=,tag:9+UQXww54ufJtA8vEMTdwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
