---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: metallb
  namespace: metallb-system
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 128Mi
    limits.cpu: 500m
    limits.memory: 512Mi
